export const topics = [
  "Art & Photography",
  "Biographies & Memoirs",
  "Business & Economics",
  "How-To & Self Help",
  "Children's Books",
  "Dictionaries",
  "Education & Teaching",
  "Fiction & Literature",
  "Magazines",
  "Medical & Health",
  "Parenting & Relationships",
  "Reference",
  "Science & Technology",
  "History & Politics",
  "Travel & Tourism",
  "Cookbooks & Food",
  "Other",
];
